Fixed scope
AngeloCore/discord-buttons pull request #109
Opened 2021-06-28 09:53 UTC by Tolfx

Instead of declaring discord-button, I just moved everything outside the scope and added "exported", since in package.json declares that types is index.d.ts, which will solve the issue meaning declaring discord-button is a bit usless. So this should solve the issue.

2021-06-28 10:05 UTC, Tolfx commented on typings/index.d.ts
> +    export default function (client: discord.Client): void;
Had to leave this, otherwise typescript would complain there is a "default" export which goes against it, so using this method saves us.

2021-06-29 16:43 UTC, DeltaCoderr approved these changes

2021-07-01 20:53 UTC, Tolfx commented
Seems like someone else is fixing the typings, closing this `PR`.

2021-07-02 06:55 UTC, AngeloCore commented
Resolve the conflicts and we will merge

2021-07-02 10:20 UTC, Tolfx commented
Added the new classes, aka MessageMenu and MessageMenuOption. Might need to fix it up a bit more, and try if it actually works. Also need to check if any new major changes as well.

2021-07-02 10:54 UTC, Assassin-1234 approved these changes

2021-07-02 11:34 UTC, DeltaCoderr approved these changes

2021-07-02 12:24 UTC, AngeloCore requested changes

2021-07-02 12:24 UTC, AngeloCore commented on typings/index.d.ts
> +  component: MessageButton;
Add `MessageMenu`

2021-07-02 12:24 UTC, AngeloCore commented on typings/index.d.ts
> +  components: MessageButton[];
Add `MessageMenu` here too

2021-07-02 12:24 UTC, AngeloCore commented on typings/index.d.ts
> +  addComponents(...components: MessageButton[]): MessageActionRow;
Add `MessageMenu` here too

2021-07-02 12:24 UTC, AngeloCore commented on typings/index.d.ts
> +  addComponent(component: MessageButton): MessageActionRow;
Add `MessageMenu` here too

2021-07-02 12:24 UTC, AngeloCore commented on typings/index.d.ts
> +  public addOptions(...options: MessageMenuOption[]): MessageMenu;
Make `MessageMenuOption` non Array

2021-07-02 12:24 UTC, AngeloCore commented on typings/index.d.ts
> +  buttons?: MessageButton | MessageButton[];
add `menu` and `menus` options

2021-07-02 12:24 UTC, AngeloCore commented on typings/index.d.ts
Add `MenuCollector`, `MessageMenuCollectorOptions` and `AwaitMessageMenuOptions`

2021-07-02 12:24 UTC, AngeloCore commented on typings/index.d.ts
> +  send(content: StringResolvable, options: MessageButton | MessageActionRow): Promise<Message | Message[]>;
Add `MessageMenu` as option

2021-07-02 12:24 UTC, AngeloCore commented on typings/index.d.ts
> +  send(content: StringResolvable, options: MessageButton | MessageActionRow): Promise<Message | Message[]>;
Add `MessageMenu` as option

2021-07-02 12:24 UTC, AngeloCore commented on typings/index.d.ts
> +  send(content: StringResolvable, options: MessageButton | MessageActionRow): Promise<Message | Message[]>;
Add `MessageMenu` as option

2021-07-02 12:24 UTC, AngeloCore commented on typings/index.d.ts
>  }
Add `multipleImport` function

2021-07-02 12:34 UTC, Tolfx commented on typings/index.d.ts
>  }
Mind if you elaborate a bit more?

2021-07-02 12:34 UTC, Tolfx commented on typings/index.d.ts
Mind if you elaborate a bit more?

2021-07-02 12:34 UTC, Tolfx commented on typings/index.d.ts
> +  buttons?: MessageButton | MessageButton[];
Mind if you elaborate a bit more?

2021-07-02 12:34 UTC, Tolfx commented on typings/index.d.ts
> +  addComponent(component: MessageButton): MessageActionRow;
Mind if you elaborate a bit more?

2021-07-02 12:35 UTC, Tolfx commented on typings/index.d.ts
> +  addComponents(...components: MessageButton[]): MessageActionRow;
Mind if you elaborate a bit more?

2021-07-02 12:35 UTC, Tolfx commented on typings/index.d.ts
> +  components: MessageButton[];
Mind if you elaborate a bit more?

2021-07-02 12:35 UTC, Tolfx commented on typings/index.d.ts
> +  component: MessageButton;
Mind if you elaborate a bit more?

2021-07-02 12:36 UTC, Tolfx commented on typings/index.d.ts
> +  public addOptions(...options: MessageMenuOption[]): MessageMenu;
Has to be an array otherwise it complains on the spread operator.
![image](https://user-images.githubusercontent.com/57797792/124275459-d69efc00-db42-11eb-9b4f-f98150aa8bcd.png)

2021-07-02 13:10 UTC, Tolfx commented on typings/index.d.ts
> +  component?: MessageButton | MessageActionRow;
Should this have MessageMenu?

2021-07-02 13:10 UTC, Tolfx commented on typings/index.d.ts
> +  components?: MessageActionRow[];
Should this have MessageMenu[]?

2021-07-02 13:11 UTC, Tolfx commented on typings/index.d.ts
> +  buttons?: MessageButton | MessageButton[];
i assume the commit has solved this issue, mind looking at it?

2021-07-02 13:12 UTC, Tolfx commented on typings/index.d.ts
The new commits should have solved it, take a look if correct.

2021-07-02 17:36 UTC, AngeloCore commented on typings/index.d.ts
> +  components?: MessageActionRow[];
yes

2021-07-02 17:36 UTC, AngeloCore commented on typings/index.d.ts
> +  component?: MessageButton | MessageActionRow;
yes

2021-07-02 17:37 UTC, AngeloCore commented on typings/index.d.ts
>  }
```ts
export function multipleImport(...clients: discord.Client): void;
```

2021-07-02 21:04 UTC, Tolfx commented on typings/index.d.ts
> +  component?: MessageButton | MessageActionRow;
Finished.

2021-07-02 21:05 UTC, Tolfx commented on typings/index.d.ts
> +  components?: MessageActionRow[];
Finished

2021-07-02 21:10 UTC, Tolfx commented on typings/index.d.ts
>  }
Finished.

2021-07-03 05:21 UTC, AngeloCore approved these changes

2021-07-03 05:22 UTC, merged