✨Code-Cleanups and Enhancing README
AngeloCore/discord-buttons pull request #74
Opened 2021-06-05 06:59 UTC by Lebyy

2021-06-05 07:25 UTC, EhsanFox commented
Readme and stuff are unnecessary!

2021-06-05 07:47 UTC, Lebyy commented
> Readme and stuff are unnecessary!

1. The current code errors had alot of grammar errors.
2. The README wasn't convincing enough
3. This PR makes the code easy to read.

2021-06-05 07:48 UTC, Lebyy commented
oops didn't mean to close it

2021-06-07 07:42 UTC, AngeloCore requested changes
Check

2021-06-08 20:53 UTC, honkling commented on src/index.js
> +  if (version < 11 || version === 11) {
Why not do version <= 11 instead?

2021-06-10 12:17 UTC, AngeloCore commented
@Lebyy so?

2021-06-18 12:53 UTC, AngeloCore commented
Inactive

2021-06-18 12:53 UTC, closed without merging