In-Progress PR | New Features
AngeloCore/discord-buttons pull request #84
Opened 2021-06-11 18:08 UTC by EhsanFox

There is a lot of stuff that I'm working on so, don't mind it yet.

2021-06-11 19:39 UTC, es183923 commented on src/index.js
> +    if (version < 11 || version === 11)
why not just use 
```js
    if (version <= 11)
```

2021-06-11 19:57 UTC, AngeloCore requested changes
Styles

2021-06-11 19:57 UTC, AngeloCore commented on src/v12/Classes/MessageButton.js
> +        this.style = 'style' in data ? resolveStyle(data.style) : resolveStyle("blurple");
You should use [`MessageButtonStyles[]`](https://github.com/AngeloCore/discord-buttons/blob/main/src/v12/Constants.js#L3)

2021-06-11 19:57 UTC, AngeloCore commented on src/v13/Classes/MessageButton.js
> +        this.style = 'style' in data ? resolveStyle(data.style) : resolveStyle("blurple");
You should use [`MessageButtonStyles[]`](https://github.com/AngeloCore/discord-buttons/blob/main/src/v12/Constants.js#L3)

2021-06-11 19:59 UTC, EhsanFox commented on src/v12/Classes/MessageButton.js
> +        this.style = 'style' in data ? resolveStyle(data.style) : resolveStyle("blurple");
`MessageButtonStyles['blurple']`
????

2021-06-11 20:04 UTC, AngeloCore commented on src/v12/Classes/MessageButton.js
> +        this.style = 'style' in data ? resolveStyle(data.style) : resolveStyle("blurple");
`MessageButtonStyles.blurple`

2021-06-11 20:05 UTC, AngeloCore commented on src/v12/Classes/MessageButton.js
> +        this.style = 'style' in data ? resolveStyle(data.style) : resolveStyle("blurple");
[Import](https://github.com/AngeloCore/discord-buttons/blob/main/src/v12/Util.js#L1)
[Use](https://github.com/AngeloCore/discord-buttons/blob/main/src/v12/Util.js#L9)

2021-06-11 20:07 UTC, EhsanFox commented on src/v12/Classes/MessageButton.js
> +        this.style = 'style' in data ? resolveStyle(data.style) : resolveStyle("blurple");
Well `MessageButtonStyles['blurple']` is the same as `MessageButtonStyles.blurple` but ok, will do tomorrow

2021-06-11 20:07 UTC, AngeloCore commented on src/v12/Classes/MessageButton.js
> +        this.style = 'style' in data ? resolveStyle(data.style) : resolveStyle("blurple");
You're using `resolveStyle()`...

2021-06-11 20:08 UTC, EhsanFox commented on src/v12/Classes/MessageButton.js
> +        this.style = 'style' in data ? resolveStyle(data.style) : resolveStyle("blurple");
yea i will change to the one u said tho

2021-06-11 20:18 UTC, es183923 commented on src/index.js
> +        throw new Error("INVALID_CLIENT_PROVIDED: The discord.js client is not provided or is invalid...")
no need for an ellipsis. Just use one period.

2021-06-11 20:19 UTC, EhsanFox commented on src/index.js
> +        throw new Error("INVALID_CLIENT_PROVIDED: The discord.js client is not provided or is invalid...")
good point

2021-06-13 20:25 UTC, AngeloCore approved these changes

2021-06-13 20:30 UTC, es183923 commented on src/index.js
>          throw new Error('The discord.js version must be v12 or high');
it should be `"The Discord.js version must be v12 or higher."`

2021-06-18 12:58 UTC, AngeloCore commented
Wait a second, why we need default style?

2021-06-18 12:59 UTC, rayzdev commented
> Wait a second, why we need default style?

It's not needed, but it makes some things easier because you don't have to specify a style if you want the button to be blurple anyways.

2021-06-22 15:58 UTC, DeltaCoderr approved these changes

2021-07-01 08:25 UTC, closed without merging